### ISSUE TITLE
【SwaggerUI】認証ヘッダを追加

### ISSUE THREAD

**Issue by atsumarukun** [atsumarukun/holos-auth-api#84]
# 概要
認証ヘッダを追加する.

# 詳細
認証が必要なルートに以下パラメータを追加する.
```yml
parameters:
  - in: "header"
    name: "Authorization"
    schema:
      type: "string"
    required: true
```
